package com.readywealth.trading.trade_engine.execution.domain;

public record TradingOrder(
        String orderId,
        String brokerOrderId,
        String accountId,
        long instrumentToken,
        String tradingsymbol,
        String exchange,
        TradingProduct product,
        TradingOrderType orderType,
        TradingSide side,
        int qty,
        Double price,
        Double triggerPrice,
        TradingOrderStatus status,
        int filledQty,
        double avgFillPrice,
        long createdAtEpochMs,
        long updatedAtEpochMs,
        String rejectionReason,
        TradingEventSource source,
        String scriptId,
        String reason,
        String parentOrderId,
        String exitPlanId,
        String triggerId,
        String ocoGroupId,
        TradingOrderRole role,
        boolean reduceOnly) {

    public TradingOrder(
            String orderId,
            String brokerOrderId,
            String accountId,
            long instrumentToken,
            String tradingsymbol,
            String exchange,
            TradingProduct product,
            TradingOrderType orderType,
            TradingSide side,
            int qty,
            Double price,
            Double triggerPrice,
            TradingOrderStatus status,
            int filledQty,
            double avgFillPrice,
            long createdAtEpochMs,
            long updatedAtEpochMs,
            String rejectionReason,
            TradingEventSource source,
            String scriptId,
            String reason) {
        this(
                orderId,
                brokerOrderId,
                accountId,
                instrumentToken,
                tradingsymbol,
                exchange,
                product,
                orderType,
                side,
                qty,
                price,
                triggerPrice,
                status,
                filledQty,
                avgFillPrice,
                createdAtEpochMs,
                updatedAtEpochMs,
                rejectionReason,
                source,
                scriptId,
                reason,
                null,
                null,
                null,
                null,
                TradingOrderRole.ENTRY,
                false);
    }

    public TradingOrder withStatus(TradingOrderStatus next, long updatedAtEpochMs, String rejectionReason) {
        return new TradingOrder(
                orderId,
                brokerOrderId,
                accountId,
                instrumentToken,
                tradingsymbol,
                exchange,
                product,
                orderType,
                side,
                qty,
                price,
                triggerPrice,
                next,
                filledQty,
                avgFillPrice,
                createdAtEpochMs,
                updatedAtEpochMs,
                rejectionReason,
                source,
                scriptId,
                reason,
                parentOrderId,
                exitPlanId,
                triggerId,
                ocoGroupId,
                role,
                reduceOnly);
    }

    public TradingOrder withBrokerOrderId(String brokerOrderId, long updatedAtEpochMs) {
        return new TradingOrder(
                orderId,
                brokerOrderId,
                accountId,
                instrumentToken,
                tradingsymbol,
                exchange,
                product,
                orderType,
                side,
                qty,
                price,
                triggerPrice,
                status,
                filledQty,
                avgFillPrice,
                createdAtEpochMs,
                updatedAtEpochMs,
                rejectionReason,
                source,
                scriptId,
                reason,
                parentOrderId,
                exitPlanId,
                triggerId,
                ocoGroupId,
                role,
                reduceOnly);
    }

    public TradingOrder withMutableFields(
            Integer qty,
            Double price,
            Double triggerPrice,
            long updatedAtEpochMs) {
        return new TradingOrder(
                orderId,
                brokerOrderId,
                accountId,
                instrumentToken,
                tradingsymbol,
                exchange,
                product,
                orderType,
                side,
                qty == null ? this.qty : qty,
                price == null ? this.price : price,
                triggerPrice == null ? this.triggerPrice : triggerPrice,
                status,
                filledQty,
                avgFillPrice,
                createdAtEpochMs,
                updatedAtEpochMs,
                rejectionReason,
                source,
                scriptId,
                reason,
                parentOrderId,
                exitPlanId,
                triggerId,
                ocoGroupId,
                role,
                reduceOnly);
    }
}
